# Generated by Django 3.1.1 on 2020-09-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatentEmbedding',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('embedding', models.TextField()),
            ],
            options={
                'db_table': 'patent_embedding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatentNgram',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngram_words', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patent_ngram',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patentsview',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'patentsview',
                'managed': False,
            },
        ),
    ]
