# Generated by Django 3.1.1 on 2020-10-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patent_search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatentNgram',
        ),
    ]
